### ISSUE TITLE
Bug/incident: LASERHEAD does not damage Lara

### ISSUE THREAD

**Issue by Frjttr** [MontyTRC89/TombEngine#1290] opened 2023-12-17 16:49 UTC
Laserhead apparently does not damage Lara on certain conditions. In my case, Laserhead is in room 64, activated in the same room (but this is not influent as the bug comes up even with the activator placed in the previous room) and Lara spawns in room 0. If I move the spawn point for Lara into the room before the LASERHEAD one + activating it in the "LASERHEAD room", it works fine and the lasers burn+kill Lara. If I chose the starting point somewhere like 5 rooms before, the Laserhead does not damage Lara.

**Comment by FedePLD** [comment] 2023-12-17 17:03
Also, crossbow darts do not break the eyes, making it impossible to kill without a Revolver/HK

**Comment by Lwmte** [comment] 2023-12-18 00:22
> Also, crossbow darts do not break the eyes, making it impossible to kill without a Revolver/HK

Are you sure it's not intended behaviour? Crossbow was not available in Rome section of TR5?

**Comment by FedePLD** [comment] 2023-12-18 07:17
Being the aim of Tomb Engine to merge together every TR Classic object, they should be able to interact regardless. It is an unintended but expected behaviour that should be fixed. The crossbow is one of the 3 weapons that can go together with a Lasersight, which is the only way to kill the Laserhead…

**Comment by Lwmte** [comment] 2023-12-18 20:02
I agree, I am just trying to understand if it is OG bug or not

**Comment by FedePLD** [comment] 2023-12-18 20:13
Oh absolutely, I think that's the issue :) Weird that the darts are managed completely different than bullets. Same for Pierre, he is immune to rocket launcher and I suspect is the same for the eyes of the LASERHEAD.

**Comment by Lwmte** [comment] 2024-10-01 21:22
Any updates on testing if this bug is OG or not?

**Comment by Jakub768** [comment] 2024-11-03 15:03
fixed in TEN 1.5

**Closed by Jakub768** 2024-11-03 15:03 UTC
Labels: Bug, LegacyTesting, Effect enchancement
