### ISSUE TITLE
[ bug Report ] Flipmap status is no longer saved

### ISSUE THREAD

**Issue by TrainWrack** [MontyTRC89/TombEngine#1447] opened 2024-11-02 23:06 UTC
### TombEngine version

v1.5 (development build)

### Tomb Editor version

v1.7.2 (development version)

### Describe the bug

The flipmaps turn off after loading a savegame.

### To Reproduce

Make a flipmap. Turn it on. Then save the game and reload. The flipmap would turn off.

### Expected Behaviour

The flipmap status should be saved and reloaded.

### Minimal reproduction project

[Revolution_Test.zip](https://github.com/user-attachments/files/17608633/Revolution_Test.zip)
Requires a switch object in SwitchType4 slot.

**Comment by Jakub768** [comment] 2024-11-03 12:38
caused by https://github.com/MontyTRC89/TombEngine/pull/1445

**Comment by Lwmte** [comment] 2024-11-08 22:11
Fixed in #751

**Closed by Lwmte** 2024-11-08 22:11 UTC
Labels: Todo
