### ISSUE TITLE
Horseman: gets killed instantly after 1 shot from grenade gun/rocket launcher

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#559] opened 2022-06-23 09:37 UTC
https://streamable.com/j4ycuy

**Comment by Adngel** [comment] 2023-11-14 14:25
I can't reproduce the bug anymore.

When I kill the horsman with a grenade, it explodes in pieces like other entities.

If increase the hitpoints, the grenade launcher doesn't kill it, instead damage it with 30 some points (what is more than its common life of 25 hitpoints).

**Comment by Adngel** [comment] 2023-11-14 14:31
Maybe has been fixed with the different updates. Please report again if bug reappears.

**Closed by Adngel** 2023-11-14 14:31 UTC
Labels: Bug
